### ISSUE TITLE
Migrate existing pieces to new pluggable component architecture, part 1 clean up the unused pieces

### ISSUE THREAD

**Issue by tlvu** [bird-house/birdhouse-deploy#214]
The following are scheduled to be removed:

```
  frontend:
    image: pavics/pavics-frontend:1.0.5
  project-api:
    image: pavics/pavics-project-api:0.9.0
  catalog:
    image: pavics/pavics-datacatalog:0.6.11
  solr:
    image: pavics/solr:5.2.1
  ncwms2:
    image: pavics/ncwms2:2.0.4
```

Includes finding and removing all references from
* configs of those components above, and remove the following unused directory `birdhouse/config/ncops`
* canarie-api, magpie and other remaining components if exist
* notebooks tested by Jenkins only.  Other notebooks are not included.
